[build]
  publish = "public"

[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
